# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate specials
#
# To automatically set Mojo to use the Python environment when you activate it:
#
#   $ mkdir -p $CONDA_PREFIX/etc/conda/activate.d
#   $ export MOJO_PYTHON_LIBRARY="$(find $CONDA_PREFIX/lib -iname 'libpython*.[s,d]*' | sort -r | head -n 1)"
#   $ echo "export MOJO_PYTHON_LIBRARY=\"$MOJO_PYTHON_LIBRARY\"" > $CONDA_PREFIX/etc/conda/activate.d/export-mojo.sh
#
#   $ mkdir -p $CONDA_PREFIX/etc/conda/deactivate.d
#   $ echo "unset MOJO_PYTHON_LIBRARY" > $CONDA_PREFIX/etc/conda/deactivate.d/unset-mojo.sh
#
name: specials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - mpmath==1.3.0
  - numpy==1.26.0
  - scipy==1.11.3
  - pip:
      - tabulate==0.9.0
      # For testing
      - pytest>=7.4.*
      - git+https://github.com/guidorice/mojo-pytest.git@v24.1.1#egg=pytest-mojo
